"Basic settings
set nocompatible
filetype plugin indent on

source ~/.dotfiles/vim/basicconfig
source ~/.dotfiles/vim/filesearch
source ~/.dotfiles/vim/headerswap
source ~/.dotfiles/vim/keyboardbinds
source ~/.dotfiles/vim/plugins
