#!/bin/sh

bspc config border_width        1
bspc config window_gap          8

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d {term,web,code,files,soc,media}
    let i++
done
NMON=$i
unset i

bspc config top_padding 16

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config focused_locked_border_color "#333333"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# colors
bspc config focused_border_color "#F06400"
bspc config active_border_color "#F06400"
bspc config normal_border_color "#232826"
bspc config presel_border_color "#5080C9"
bspc config urgent_border_color "#EF5847"

i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor \
         -n "$i" \
         -d {i,ii,iii,iv,v,vi,vii,viii,ix,x}
    let i++
done
NMON=$i
unset i
