#!/bin/sh

xset +fp /usr/share/fonts/misc
xset +fp /usr/share/fonts/local
xset fp rehash

[ -f $userresources ] && xrdb -merge $HOME/.Xresources

function connection_strength() {
    n=$(echo "(`iwconfig | grep Signal | cut -d' ' -f15 | cut -d'=' -f2 | cut -d'/' -f1` / 33)" | bc)
    for i in `seq $n`; do echo -n '.'; done
}

while true
do
	echo "`date "+%H:%M"` %{c} wi `connection_strength`"
done | lemonbar -f '-*-creep-regular-*-*--16-*-*-*-*-*-*-1' -B \#232826 &

sxhkd -c $HOME/.sxhkdrc &

# Start clipboard manager
xcmenu -d &

# Normal cursor
xsetroot -cursor_name left_ptr

# Touchscreen shizzle
touchegg &

# Hide mouse
xbanish &

sh ~/.fehbg &

exec bspwm
